FinalProductApp/BackupApp/main/default/objects/Product2/fields/Product_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product External Id</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

FinalProductApp/BackupApp/main/default/objects/Product_Backup__c/Product_Backup__c.object-meta.xml
<CustomObject>
   
    <description>to reflect the product2 items here.</description>
    <label>Product Backup</label>
    <nameField>
        <label>Product Backup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Backups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FinalProductApp/BackupApp/main/default/objects/Product_Backup__c/fields/Product_External_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_External_Id__c</fullName>
    <externalId>true</externalId>
    <label>Product External Id</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

FinalProductApp/BackupApp/main/default/classes/ProductBackupCtrlTest.cls
@isTest
public class ProductBackupCtrlTest {
    
    static testMethod void testProductSyncBatch() {
        Product2 prd = TestDataFactory.createProduct();
        Pricebook2 pb = TestDataFactory.createPriceBook();
        PriceBookEntry pbeRec = TestDataFactory.createPriceBookEntry(prd);
        Product_Backup__c bkpRec = TestDataFactory.createProductBackup();
        Test.startTest();
        ProductBackupCtrl.ProductWrapper prodWrap = ProductBackupCtrl.getProductDetails(bkpRec.Id);
        
        Test.stopTest();
        System.assertEquals('8913761232193', prodWrap.prodExternalId);
        System.assertEquals(true, [Select isActive from Product2 where Product_External_Id__c =: prodWrap.prodExternalId].isActive);
        
    }
}